"""Deterministic scaffold generator — manifest → project CLAUDE.md + manifest + scaffold plan.

Produces the onboarding *context and plan* (not a full compilable repo tree — that is the LLM-driven
eeik repository-generator, a follow-on). Pure and offline.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

import yaml

from .capability_resolver import Resolution
from .eeik_engine import EeikEngine, VendoredEeikEngine
from .manifest import ProjectManifest

_TEMPLATE = Path(__file__).parent / "eeik_assets" / "templates" / "project-claude-md.md"


@dataclass
class OnboardingResult:
    """Everything the onboarding front door produces for one project."""

    project_name: str
    entry_phase: str
    manifest: dict[str, Any]
    packs: list[dict[str, Any]]
    reviews_required: list[str]
    compliance_hints: list[str]
    recommended_agents: list[str]
    governance_required: bool
    claude_md: str
    manifest_yaml: str
    scaffold_plan: str = field(default="")
    eeik_source: str = field(default="vendored")  # provenance: "vendored" | "repo:<path>"

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    def files(self) -> dict[str, str]:
        """filename → content, for the demo to write to disk."""
        return {
            "CLAUDE.md": self.claude_md,
            "project-manifest.yaml": self.manifest_yaml,
            "scaffold-plan.md": self.scaffold_plan,
        }


def build_scaffold(
    manifest: ProjectManifest,
    entry_phase: str = "requirements",
    engine: EeikEngine | None = None,
) -> OnboardingResult:
    """Resolve packs and generate the CLAUDE.md, normalized manifest, and scaffold plan.

    ``engine`` selects the resolution source; it defaults to the vendored engine so the offline demo and
    tests stay byte-reproducible. The onboarding API passes a repo engine when one is configured.
    """
    engine = engine or VendoredEeikEngine()
    res = engine.resolve(manifest)
    packs = [
        {"name": p.name, "availability": p.availability, "selected_by": p.selected_by} for p in res.packs
    ]
    manifest_yaml = yaml.safe_dump(manifest.model_dump(exclude_none=True), sort_keys=False)
    claude_md = _render_claude_md(manifest, res)
    scaffold_plan = _render_scaffold_plan(manifest, res, entry_phase)
    return OnboardingResult(
        project_name=manifest.project.name,
        entry_phase=entry_phase,
        manifest=manifest.model_dump(exclude_none=True),
        packs=packs,
        reviews_required=res.reviews_required,
        compliance_hints=res.compliance_hints,
        recommended_agents=res.recommended_agents,
        governance_required=res.governance_required,
        claude_md=claude_md,
        manifest_yaml=manifest_yaml,
        scaffold_plan=scaffold_plan,
        eeik_source=engine.source,
    )


def _render_claude_md(m: ProjectManifest, res: Resolution) -> str:
    template = _TEMPLATE.read_text(encoding="utf-8")
    packs_list = "\n".join(
        f"- `{p.name}` ({p.availability}) — selected by {', '.join(p.selected_by)}" for p in res.packs
    ) or "- (none resolved)"
    values = {
        "project_name": m.project.name,
        "project_description": m.project.description or "(no description)",
        "project_owner": m.project.owner or "(unassigned)",
        "domain": m.project.domain,
        "project_type": m.project.project_type,
        "backend_language": m.technology.backend.language,
        "backend_version": str(m.technology.backend.version or ""),
        "backend_framework": m.technology.backend.framework or "(none)",
        "frontend_framework": m.technology.frontend.framework,
        "database_type": m.technology.database.type or "(none)",
        "migration_tool": m.technology.database.migration_tool,
        "architecture_style": m.architecture.style,
        "api_style": m.architecture.api_style,
        "cloud_provider": m.cloud.provider,
        "infra_as_code": m.cloud.infra_as_code,
        "capability_packs_list": packs_list,
        "governance_profile": m.governance.profile,
        "reviews_required": ", ".join(res.reviews_required) or "none",
        "ai_governance_required": "yes" if res.governance_required else "no",
    }
    for key, val in values.items():
        template = template.replace("{" + key + "}", val)
    return template


def _render_scaffold_plan(m: ProjectManifest, res: Resolution, entry_phase: str) -> str:
    layout = _repository_layout(m)
    layout_block = "\n".join(f"  {line}" for line in layout)
    packs_block = "\n".join(
        f"| `{p.name}` | {p.availability} | {', '.join(p.selected_by)} |" for p in res.packs
    ) or "| (none) | — | — |"
    return (
        f"# Scaffold Plan — {m.project.name}\n\n"
        f"Generated by the APEX onboarding front door from an eeik manifest. This is the deterministic "
        f"scaffold *plan*; the full repo tree is emitted by the eeik repository-generator (follow-on).\n\n"
        f"## Repository layout\n\n```\n{m.project.name}/\n{layout_block}\n```\n\n"
        f"## Capability packs\n\n| Pack | Availability | Selected by |\n|---|---|---|\n{packs_block}\n\n"
        f"## Recommended eeik agents\n\n{', '.join(f'`{a}`' for a in res.recommended_agents)}\n\n"
        f"## Governance\n\n"
        f"- Profile: **{m.governance.profile}**\n"
        f"- Reviews required: {', '.join(res.reviews_required) or 'none'}\n"
        f"- AI governance required: **{'yes' if res.governance_required else 'no'}**\n"
        f"- Compliance hints: {', '.join(res.compliance_hints) or 'none'}\n\n"
        f"## APEX hand-off\n\n"
        f"Registered in APEX at the **{entry_phase}** phase — the entry point of the spec-driven spine.\n"
    )


def _repository_layout(m: ProjectManifest) -> list[str]:
    """A stack-appropriate directory plan (documented, not emitted)."""
    lines = ["CLAUDE.md", "project-manifest.yaml", "README.md"]
    lang = m.technology.backend.language
    if lang in ("java", "mixed"):
        lines += [
            "pom.xml",
            "src/main/java/…/domain/",
            "src/main/java/…/application/",
            "src/main/java/…/infrastructure/",
            "src/main/java/…/web/",
            "src/test/java/…/",
        ]
    if lang in ("python", "mixed"):
        lines += [
            "pyproject.toml",
            "app/api/",
            "app/core/",
            "app/models/",
            "app/schemas/",
            "app/services/",
            "tests/",
        ]
    if m.technology.frontend.framework != "none":
        lines.append(f"frontend/  ({m.technology.frontend.framework})")
    if m.cloud.infra_as_code in ("cdk", "terraform", "both"):
        lines.append(f"infra/  ({m.cloud.infra_as_code})")
    lines.append(".github/workflows/ci.yml")
    return lines
