"""
APEX Confluence Page Templates
Pre-built HTML templates for common APEX-generated page types.
"""

SPRINT_KICKOFF = """
<h1>Sprint Kickoff — {sprint_name}</h1>
<p><strong>Goal:</strong> {sprint_goal}</p>
<hr/>
<h2>AI Digest</h2>
<p>{ai_digest}</p>
<hr/>
<h2>Committed Stories</h2>
{story_table}
<p><em>Generated by APEX Jira Bridge on {generated_at}</em></p>
"""

SPRINT_CLOSE = """
<h1>Sprint Close Summary — {sprint_name}</h1>
<table>
  <tr><th>Committed SP</th><th>Completed SP</th><th>Velocity %</th></tr>
  <tr><td>{committed}</td><td>{completed}</td><td>{velocity_pct}%</td></tr>
</table>
<hr/>
<h2>AI Summary</h2>
<p>{ai_summary}</p>
<h2>Carry-forward ({carry_count} stories)</h2>
{carry_table}
<p><em>Generated by APEX Jira Bridge on {generated_at}</em></p>
"""

ISSUE_BRIEF = """
<h1>APEX AI Brief — {issue_key}</h1>
<p><strong>Summary:</strong> {summary}</p>
<p><strong>Type:</strong> {issue_type} | <strong>Priority:</strong> {priority}</p>
<hr/>
<h2>Stakeholder Brief</h2>
<p>{ai_brief}</p>
<p><em>Generated by APEX Jira Bridge · Model: {model}</em></p>
"""

RELEASE_NOTES = """
<h1>Release Notes — {version}</h1>
<p><strong>Release Date:</strong> {release_date}</p>
<hr/>
<h2>What's New</h2>
{features}
<h2>Bug Fixes</h2>
{bug_fixes}
<h2>Improvements</h2>
{improvements}
<h2>Security</h2>
{security}
<hr/>
<h2>Stakeholder Summary</h2>
<p>{stakeholder_summary}</p>
<p><em>Generated by APEX Release Pipeline on {generated_at}</em></p>
"""


def story_table_html(issues: list[dict]) -> str:
    """Render a list of Jira issue dicts as an HTML table."""
    if not issues:
        return "<p><em>No stories.</em></p>"
    rows = "\n".join(
        f"<tr><td>{i.get('key','')}</td><td>{i['fields']['summary']}</td>"
        f"<td>{i['fields']['issuetype']['name']}</td>"
        f"<td>{i['fields'].get('story_points','?')} SP</td></tr>"
        for i in issues
    )
    return f"""<table>
  <tr><th>Key</th><th>Summary</th><th>Type</th><th>Points</th></tr>
  {rows}
</table>"""
